name: Pull Request Common

on:  pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Build NuGet Packages
      run: dotnet pack -c Release -o ./nuget
    - name: Deploy NuGet Packages
      run: |
        dotnet nuget push /home/runner/work/gratisdns/gratisdns/nuget/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}